make:
	# g++ -g -std=c++11 client_r_udp.cpp -o client_r_udp
	# g++ -g -std=c++11 server_r_udp.cpp -o server_r_udp
	# g++ -g -std=c++11 trial.cpp -o trial
	# 
	g++ -g -std=c++11 client_udp.cpp -o client_udp
	g++ -g -std=c++11 server_udp.cpp -o server_udp
	g++ -g -std=c++11 file_trial.cpp -o file_trial
	

clean:
	#  rm -rf client_r_udp
	#  rm -rf server_r_udp
	#  rm -rf trial 
	rm -rf client_udp
	rm -rf server_udp
	rm -rf file_trial 
	rm -rf *.dSYM
