make:
	g++ -g -std=c++11 client_r_udp.cpp -o client_r_udp
	g++ -g -std=c++11 server_r_udp.cpp -o server_r_udp
	g++ -g -std=c++11 trial.cpp -o trial

clean:
	rm -rf client_r_udp
	rm -rf server_r_udp
	rm -rf trial 
	rm -rf *.dSYM
